site_name: Munity Unified API
site_url: https://docs.munityapps.com
repo_url: https://github.com/munityapps/unified-api-docs
repo_name: Munity Unified API Documentation repository
site_description: This documentation provide information to use Munity Unified API
site_author: Cyril ALFARO
copyright: GPL3
remote_branch: gh-pages
remote_name: origin

theme: material

nav:
  - Overview: index.md
  - Getting started: getting-started.md
  - How to : 
    - Use frontend SDK: howtousefrontend.md
    - Access data : howtousebackend.md
  - API Reference: 'https://app.swaggerhub.com/apis-docs/CYRIL_8/munity-unified_api/'
  - Webhook Reference: webhooks.md
  - Create Order: create-order.md

docs_dir: docs
site_dir: site
