site_name: Munity Unified API
site_url: https://docs.munityapps.com
repo_url: https://github.com/munityapps/unified-api-docs
repo_name: Munity Unified API Documentation repository
site_descroption: This documentation provide information to use Munity Unified API
site_author: Cyril ALFARO
copyright: GPL3
remote_branch: gh-pages
remote_name: origin

theme: material

nav:
  - Overview: index.md
  - Configure: configure.md
  - How to use : 
    - Use munity frontend SDK: howtousefrontend.md
    - Get access to your customer data: howtousebackend.md
  - API Reference: 'https://app.swaggerhub.com/apis-docs/dbyzero/munity-unified_api/'
  - Webhook Reference: webhooks.md

docs_dir: docs
site_dir: site

